version: '3'
services: 
  redis:
    image: 'bitnami/redis:4.0'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'
  node-app:
    build: .
    ports:
      - "8081:8081"
    links:
      - redis

volumes:
  redis_data:
    driver: local
